chore(deps): update dependencies (#116)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[@types/node](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node)
([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node))
| [`20.10.7` ->
`20.11.0`](https://renovatebot.com/diffs/npm/@types%2fnode/20.10.7/20.11.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2fnode/20.11.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2fnode/20.11.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2fnode/20.10.7/20.11.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2fnode/20.10.7/20.11.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@typescript-eslint/eslint-plugin](https://togithub.com/typescript-eslint/typescript-eslint)
([source](https://togithub.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/eslint-plugin))
| [`6.18.0` ->
`6.18.1`](https://renovatebot.com/diffs/npm/@typescript-eslint%2feslint-plugin/6.18.0/6.18.1)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@typescript-eslint%2feslint-plugin/6.18.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@typescript-eslint%2feslint-plugin/6.18.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@typescript-eslint%2feslint-plugin/6.18.0/6.18.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@typescript-eslint%2feslint-plugin/6.18.0/6.18.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[eslint-plugin-n](https://togithub.com/eslint-community/eslint-plugin-n)
| [`16.6.1` ->
`16.6.2`](https://renovatebot.com/diffs/npm/eslint-plugin-n/16.6.1/16.6.2)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/eslint-plugin-n/16.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/eslint-plugin-n/16.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/eslint-plugin-n/16.6.1/16.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/eslint-plugin-n/16.6.1/16.6.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [prettier](https://prettier.io)
([source](https://togithub.com/prettier/prettier)) | [`3.1.1` ->
`3.2.1`](https://renovatebot.com/diffs/npm/prettier/3.1.1/3.2.1) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/prettier/3.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/prettier/3.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/prettier/3.1.1/3.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier/3.1.1/3.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[semantic-release](https://togithub.com/semantic-release/semantic-release)
| [`22.0.12` ->
`23.0.0`](https://renovatebot.com/diffs/npm/semantic-release/22.0.12/23.0.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/semantic-release/23.0.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/semantic-release/23.0.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/semantic-release/22.0.12/23.0.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/semantic-release/22.0.12/23.0.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>typescript-eslint/typescript-eslint
(@&#8203;typescript-eslint/eslint-plugin)</summary>

###
[`v6.18.1`](https://togithub.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/eslint-plugin/CHANGELOG.md#6181-2024-01-08)

[Compare
Source](https://togithub.com/typescript-eslint/typescript-eslint/compare/v6.18.0...v6.18.1)

##### 🩹 Fixes

- **eslint-plugin:** \[no-non-null-assertion] provide valid fix when
member access is on next line

- **eslint-plugin:** \[no-unnecessary-condition] improve checking
optional callee

- **eslint-plugin:** \[prefer-readonly] support modifiers of unions and
intersections

- **eslint-plugin:** \[switch-exhaustiveness-check] fix new
allowDefaultCaseForExhaustiveSwitch option

##### ❤️  Thank You

-   auvred
-   James
-   Josh Goldberg ✨
-   YeonJuan

You can read about our [versioning
strategy](https://main--typescript-eslint.netlify.app/users/versioning)
and
[releases](https://main--typescript-eslint.netlify.app/users/releases)
on our website.

</details>

<details>
<summary>eslint-community/eslint-plugin-n (eslint-plugin-n)</summary>

###
[`v16.6.2`](https://togithub.com/eslint-community/eslint-plugin-n/releases/tag/16.6.2)

[Compare
Source](https://togithub.com/eslint-community/eslint-plugin-n/compare/16.6.1...16.6.2)

- fix: no-callback-literal ignore unknown nodes
([#&#8203;163](https://togithub.com/eslint-community/eslint-plugin-n/issues/163))
([`5fc2198`](https://togithub.com/eslint-community/eslint-plugin-n/commit/5fc2198))

</details>

<details>
<summary>prettier/prettier (prettier)</summary>

###
[`v3.2.1`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#321)

[Compare
Source](https://togithub.com/prettier/prettier/compare/3.2.0...3.2.1)

[diff](https://togithub.com/prettier/prettier/compare/3.2.0...3.2.1)

##### Fix formatting error on member chain
([#&#8203;15915](https://togithub.com/prettier/prettier/pull/15915) by
[@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))

<!-- prettier-ignore -->

```jsx
// Input
test().test2().test2(thing?.something);

// Prettier 3.2.0
TypeError: Cannot read properties of undefined (reading 'type')

// Prettier 3.2.1
test().test2().test2(thing?.something);

```

###
[`v3.2.0`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#320)

[Compare
Source](https://togithub.com/prettier/prettier/compare/3.1.1...3.2.0)

[diff](https://togithub.com/prettier/prettier/compare/3.1.1...3.2.0)

🔗 [Release Notes](https://prettier.io/blog/2024/01/13/3.2.0.html)

</details>

<details>
<summary>semantic-release/semantic-release (semantic-release)</summary>

###
[`v23.0.0`](https://togithub.com/semantic-release/semantic-release/releases/tag/v23.0.0)

[Compare
Source](https://togithub.com/semantic-release/semantic-release/compare/v22.0.12...v23.0.0)

##### Bug Fixes

- **deps:** update dependency cosmiconfig to v9
([#&#8203;3105](https://togithub.com/semantic-release/semantic-release/issues/3105))
([07dde04](https://togithub.com/semantic-release/semantic-release/commit/07dde042bbdd4a407dbf7f7a5b8ab2d11abdb8c3))
- **deps:** update dependency marked to v11
([#&#8203;3079](https://togithub.com/semantic-release/semantic-release/issues/3079))
([6d2a6f1](https://togithub.com/semantic-release/semantic-release/commit/6d2a6f1aa658cfdfa905f19a4c54f38ebdfc94ef))
- **deps:** upgraded to the latest version of env-ci
([0d0ed9d](https://togithub.com/semantic-release/semantic-release/commit/0d0ed9d08a26ed5e146fcba5a58d760f7a1ebd02))
- use one note reference per tag to prevent conflicts
([#&#8203;2085](https://togithub.com/semantic-release/semantic-release/issues/2085))
([020ea7d](https://togithub.com/semantic-release/semantic-release/commit/020ea7d7d5aa6c123fe4c97754b6b1b36c0a8e2c))

##### Features

- **node-versions:** dropped support for node v18 and raised the minimum
for v20
([2904832](https://togithub.com/semantic-release/semantic-release/commit/2904832967c9160d3e293ce4be7a12aef0318a95)),
closes
[/github.com/semantic-release/gitlab/pull/647#discussion_r1423131205](https://togithub.com//github.com/semantic-release/gitlab/pull/647/issues/discussion_r1423131205)

##### BREAKING CHANGES

- **deps:** woodpecker ci users need to upgrade to v1.0.0 or higher to
remain supported. see
https://github.com/semantic-release/env-ci/releases/tag/v11.0.0 for more
information
- **node-versions:** support for node v18 has been dropped and the
minimum for v20 is now v20.8.1

related to
[https://github.com/semantic-release/semantic-release/discussions/3088](https://togithub.com/semantic-release/semantic-release/discussions/3088)

- **deps:** if using `release.config.js` as the name of your config
file, it needs to be moved to a `.config/` directory. see
https://github.com/cosmiconfig/cosmiconfig/releases/tag/v9.0.0 for more
detail

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "every weekend" (UTC), Automerge - At
any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config help](https://togithub.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/xkrishguptaa/trevenant).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy4xMjcuMCIsInVwZGF0ZWRJblZlciI6IjM3LjEyNy4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiJ9-->

Signed-off-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>